version: '3'
services:
  mail:
    build: .
    ports:
      - "25:25"
      - "587:587"
      - "995:995"
      - "80:80"
    volumes:
       - maildata:/var/vmail
    environment:
      EMAIL_DOMAIN: example.com
      RELAY_ADDRESS: api:10025
      CERTBOT_EMAIL: test@test.com
      USE_LETSENCRYPT: "no"
      MAIL_USERNAME: username
      MAIL_PASSWORD: password

volumes:
  maildata:
